// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedFile struct {
	ID          pgtype.UUID        `json:"id"`
	FileName    string             `json:"file_name"`
	Checksum    string             `json:"checksum"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
