// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProcessedFile(ctx context.Context, arg CreateProcessedFileParams) error
	FindByChecksum(ctx context.Context, checksum string) (ProcessedFile, error)
}

var _ Querier = (*Queries)(nil)
