// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessedFile = `-- name: CreateProcessedFile :exec
INSERT INTO processed_files (id, file_name, checksum, processed_at)
VALUES ($1, $2, $3, $4)
`

type CreateProcessedFileParams struct {
	ID          pgtype.UUID        `json:"id"`
	FileName    string             `json:"file_name"`
	Checksum    string             `json:"checksum"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) CreateProcessedFile(ctx context.Context, arg CreateProcessedFileParams) error {
	_, err := q.db.Exec(ctx, createProcessedFile,
		arg.ID,
		arg.FileName,
		arg.Checksum,
		arg.ProcessedAt,
	)
	return err
}

const findByChecksum = `-- name: FindByChecksum :one
SELECT id, file_name, checksum, processed_at
FROM processed_files
WHERE checksum = $1
LIMIT 1
`

func (q *Queries) FindByChecksum(ctx context.Context, checksum string) (ProcessedFile, error) {
	row := q.db.QueryRow(ctx, findByChecksum, checksum)
	var i ProcessedFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Checksum,
		&i.ProcessedAt,
	)
	return i, err
}
